import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { ErrorWrapper } from './error-wrapper';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: {
    default: 'Next.js 15',
    template: '%s | Next.js 15',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="bg-blue-600 p-5 text-white">
          <p>Header</p>
        </header>

        <ErrorWrapper>{children}</ErrorWrapper>

        <footer className="bg-green-700 p-5 text-white">
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
